language: node_js

node_js:
  - "8.11.1"

notifications:
  email: false

sudo: false

branches:
  only:
    - master

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

install:
  - wget https://github.com/NebulousLabs/Sia/releases/download/v1.3.3/Sia-v1.3.3-linux-amd64.zip
  - unzip Sia-v1.3.3-linux-amd64.zip
  - mv Sia-v1.3.3-linux-amd64 Sia
  - export PATH=$PATH:`pwd`/Sia/
  - npm install

